version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore(deps)
